version: '3.5'

services:
  kotlin-restful-api:
    container_name: kotlin-restful-api
    image: kotlin-restful-api:1.0.0
    ports:
      - "8080:8080"
    networks: 
      - app-db-network
    environment:
      DATABASE_USERNAME: kotlin
      DATABASE_PASSWORD: kotlin
      DATABASE_IP: kotlin-restful-api-db
  db:
    container_name: "kotlin-restful-api-db"
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    networks: 
      - app-db-network
    environment:
      POSTGRES_PASSWORD: kotlin
      POSTGRES_USER: kotlin
      POSTGRES_DB: restful-api

networks:
  app-db-network: