## Post data
## Valid request
POST http://localhost:8080/api/products
Content-Type: application/json
Accept: application/json

{
  "id": "AB012",
  "name": "Tahu Sumedang",
  "price": 2000,
  "quantity": 10
}
###

## Post data
## Invalid Request
 POST http://localhost:8080/api/products
Content-Type: application/json
Accept: application/json

{
  "id": "",
  "name": "Tahu Bacem",
  "price": 2000,
  "quantity": -10
}
###

# get all products
GET http://localhost:8080/api/products?page=0&size=10
Content-Type: application/json
###

## Get Product By ID
GET http://localhost:8080/api/products/AB001
Content-Type: application/json
###

# Update data
# valid request
PUT http://localhost:8080/api/products/AB001
Content-Type: application/json
Accept: application/json

{
  "name": "Tahu Bacem Enak Sekali",
  "price": 2000,
  "quantity": 10
}
###

# Update Product
# Invalid request
PUT http://localhost:8080/api/products/AB001
Content-Type: application/json
Accept: application/json

{
  "name": "Tahu Bacem Enak Sekali",
  "price": 2000,
  "quantity": -10
}
###

# Delete Product
# Valid
DELETE  http://localhost:8080/api/products/AB001
Content-Type: application/json
###

# Delete Product
# Invalid
DELETE  http://localhost:8080/api/products/AB001
Content-Type: application/json